INSERT INTO employees(first_name,middle_name,last_name,street_address,city,state,zip,email) VALUES ('Cynthy','Glennis','Balch','931 Calypso Center','Salt Lake City','Utah','76914','gbalch0@delicious.com');
INSERT INTO employees(first_name,middle_name,last_name,street_address,city,state,zip,email) VALUES ('Chris','Jacky','Mayne','24150 Washington Trail','Augusta','Georgia','23491','jmayne0@spiegel.de');
INSERT INTO employees(first_name,middle_name,last_name,street_address,city,state,zip,email) VALUES ('Amber','Pip','Wands','21906 Southridge Street','Cleveland','Ohio','65133','birons6@harvard.edu');
INSERT INTO employees(first_name,middle_name,last_name,street_address,city,state,zip,email) VALUES ('Roseanna','Aland','Wroath','89 Muir Street','Lake Worth','Florida','21413','kthumnel3@independent.co.uk');
INSERT INTO employees(first_name,middle_name,last_name,street_address,city,state,zip,email) VALUES ('Abigail','Koo','Thumnel','931 Calypso Center','Aurora','Illinois','77192','gmerwood0@mapquest.com');
INSERT INTO employees(first_name,middle_name,last_name,street_address,city,state,zip,email) VALUES ('Lolita','Antoni','Gristhwaite','6291 Di Loreto Park','Reston','Virginia','96592','acalifornia6@sbwire.com');
INSERT INTO employees(first_name,middle_name,last_name,street_address,city,state,zip,email) VALUES ('Pamela','Keriann','Langstaff','1325 Chowing Center','Charleston','West Virginia', '84219','kjeanesson0@who.int');
INSERT INTO employees(first_name,middle_name,last_name,street_address,city,state,zip,email) VALUES ('Mireielle','Jeanie','Tilbury','58 Pond Lane','Chicago','Illinois','97700','klangstaff8@pagesperso-orange.fr');
INSERT INTO employees(first_name,middle_name,last_name,street_address,city,state,zip,email) VALUES ('Burk','Jerrie','Tunna','96385 Rusk Hill','Fort Worth','Texas','32837','ecrock6@nps.gov');
INSERT INTO employees(first_name,middle_name,last_name,street_address,city,state,zip,email) VALUES ('Alfonse','Roxanna','Fessler','7223 Packers Hill','Columbia','South Carolina','95372','rfessler8@4shared.com');

INSERT INTO employees_phone(employees_id,phone_number,phone_type) VALUES (1, '654-234-6521', '0');
INSERT INTO employees_phone(employees_id,phone_number,phone_type) VALUES (1, '345-645-1231', '1');
INSERT INTO employees_phone(employees_id,phone_number,phone_type) VALUES (2, '543-534-7854', '0');
INSERT INTO employees_phone(employees_id,phone_number,phone_type) VALUES (2, '123-897-4534', '1');
INSERT INTO employees_phone(employees_id,phone_number,phone_type) VALUES (3, '789-312-4564', '0');
INSERT INTO employees_phone(employees_id,phone_number,phone_type) VALUES (3, '869-123-5465', '2');
INSERT INTO employees_phone(employees_id,phone_number,phone_type) VALUES (4, '982-342-1375', '0');
INSERT INTO employees_phone(employees_id,phone_number,phone_type) VALUES (5, '898-685-4567', '1');
INSERT INTO employees_phone(employees_id,phone_number,phone_type) VALUES (6, '568-564-1237', '2');
INSERT INTO employees_phone(employees_id,phone_number,phone_type) VALUES (6, '157-535-3256', '1');
INSERT INTO employees_phone(employees_id,phone_number,phone_type) VALUES (7, '567-354-9086', '0');
INSERT INTO employees_phone(employees_id,phone_number,phone_type) VALUES (7, '134-645-7584', '1');
INSERT INTO employees_phone(employees_id,phone_number,phone_type) VALUES (8, '234-464-6314', '2');
INSERT INTO employees_phone(employees_id,phone_number,phone_type) VALUES (9, '638-964-3467', '2');
INSERT INTO employees_phone(employees_id,phone_number,phone_type) VALUES (10, '636-897-0753', '1');
INSERT INTO employees_phone(employees_id,phone_number,phone_type) VALUES (10, '907-564-2465', '0');